(define (domain detective-domain)

   (:predicates (ROOM ?x) (AGENT ?x) (KILLER ?x)
                (alive ?x) (died ?x)
                (in-room ?x ?y)
                (want-go-to ?x ?y) (knows-where-to-go ?x)
                (thinks-is-a-killer ?x ?y)
                (found-evidence-against ?x ?y)
                (scared ?x) (angry-at ?x ?y)
   )
   
(:action decide-where-to-go :parameters (?a ?place)
:precondition (and (ROOM ?place) (AGENT ?a)
                   (alive ?a)
                   (not (in-room ?a ?place))
                   (not (knows-where-to-go ?a))
               )
:effect (and (want-go-to ?a ?place) (knows-where-to-go ?a)
         )
)   

(:action agent_move :parameters (?a ?room-from ?room-to)
:precondition (and (ROOM ?room-from) (ROOM ?room-to) (AGENT ?a)
                   (alive ?a)
                   (in-room ?a ?room-from)
                   (want-go-to ?a ?room-to) (knows-where-to-go ?a)
                   (not (died ?a)) (not (in-room ?a ?room-to)))
:effect (and (in-room ?a ?room-to)
             (not (in-room ?a ?room-from))))
             
(:action killer_move :parameters (?k ?room-from ?room-to)
:precondition (and (ROOM ?room-from) (ROOM ?room-to) (KILLER ?k)
                   (alive ?k)
                   (in-room ?k ?room-from)
                   (not (died ?k)) (not (in-room ?k ?room-to)))
:effect (and (in-room ?k ?room-to)
             (not (in-room ?k ?room-from))))
             
(:action to-be-a-witness :parameters (?a ?victim ?k ?place)
:precondition (and (ROOM ?place) (AGENT ?a) (AGENT ?victim) (KILLER ?k)
                   (alive ?a) (alive ?k) (died ?victim)
                   (in-room ?a ?place) (in-room ?victim ?place) (in-room ?k ?place)
               )
:effect (and (thinks-is-a-killer ?a ?k) (angry-at ?a ?k)
         )
)
             
(:action entrap :parameters (?k ?a ?place)
:precondition (and (ROOM ?place) (KILLER ?k) (AGENT ?a)
                   (alive ?k) (alive ?a)
                   (in-room ?k ?place) (not (in-room ?a ?place))
               )
:effect (and (want-go-to ?a ?place)
         )
)
  
(:action tell-about-a-suspicious :parameters (?k ?a ?place)
:precondition (and (ROOM ?place) (KILLER ?k) (AGENT ?a)
                   (alive ?k) (alive ?a)
                   (in-room ?k ?place) (in-room ?a ?place)
               )
:effect (and (want-go-to ?a ?place)
         )
)

(:action search-the-room :parameters (?a ?place ?k)
:precondition (and (ROOM ?place) (KILLER ?k) (AGENT ?a)
                   (alive ?k) (alive ?a)
                   (in-room ?a ?place)
               )
:effect (and (found-evidence-against ?a ?k) (thinks-is-a-killer ?a ?k) (angry-at ?a ?k)
         )
)

(:action tell-about-killer :parameters (?a1 ?a2 ?place ?k)
:precondition (and (ROOM ?place) (AGENT ?a1) (AGENT ?a2) (KILLER ?k)
                   (alive ?a1) (alive ?a2) (alive ?k)
                   (in-room ?a1 ?place) (in-room ?a2 ?place)
                   (found-evidence-against ?a1 ?k)
               )
:effect (and (thinks-is-a-killer ?a2 ?k) (angry-at ?a2 ?k)
         )
)

(:action neutralize-the-killer :parameters (?a ?k ?place)
:precondition (and (ROOM ?place) (KILLER ?k) (AGENT ?a)
                   (alive ?k) (alive ?a)
                   (in-room ?a ?place) (in-room ?k ?place)
                   (angry-at ?a ?k)
               )
:effect (and (died ?k) (not (alive ?k))
         )
)

(:action kill-if-all-alive :parameters (?k ?victim ?r ?a1 ?a2 ?a3 ?a4)
:precondition (and (ROOM ?r) (KILLER ?k) (AGENT ?victim) (AGENT ?a1) (AGENT ?a2) (AGENT ?a3) (AGENT ?a4)
                   (alive ?k) (alive ?victim) (alive ?a1) (alive ?a2) (alive ?a3) (alive ?a4)
                   (in-room ?k ?r) (in-room ?victim ?r)
                   (not (in-room ?a1 ?r)) (not (in-room ?a2 ?r)) (not (in-room ?a3 ?r)) (not (in-room ?a4 ?r))
                   (not (= ?a1 ?a2)) (not (= ?a1 ?a3)) (not (= ?a1 ?a4)) (not (= ?a2 ?a3)) (not (= ?a2 ?a4)) (not (= ?a3 ?a4))
              )
                   
:effect (and (died ?victim)
             (not (alive ?victim)))
)

(:action kill-if-one-died :parameters (?k ?victim ?r ?a1 ?a2 ?a3 ?a4)
:precondition (and (ROOM ?r) (KILLER ?k) (AGENT ?victim) (AGENT ?a1) (AGENT ?a2) (AGENT ?a3) (AGENT ?a4)
                   (alive ?k) (alive ?victim) (alive ?a1) (alive ?a2) (alive ?a3) (died ?a4)
                   (in-room ?k ?r) (in-room ?victim ?r)
                   (not (in-room ?a1 ?r)) (not (in-room ?a2 ?r)) (not (in-room ?a3 ?r))
                   (not (= ?a1 ?a2)) (not (= ?a1 ?a3)) (not (= ?a1 ?a4)) (not (= ?a2 ?a3)) (not (= ?a2 ?a4)) (not (= ?a3 ?a4))
              )
                   
:effect (and (died ?victim)
             (not (alive ?victim)))
)

(:action kill-if-two-died :parameters (?k ?victim ?r ?a1 ?a2 ?a3 ?a4)
:precondition (and (ROOM ?r) (KILLER ?k) (AGENT ?victim) (AGENT ?a1) (AGENT ?a2) (AGENT ?a3) (AGENT ?a4)
                   (alive ?k) (alive ?victim) (alive ?a1) (alive ?a2) (died ?a3) (died ?a4)
                   (in-room ?k ?r) (in-room ?victim ?r)
                   (not (in-room ?a1 ?r)) (not (in-room ?a2 ?r))
                   (not (= ?a1 ?a2)) (not (= ?a1 ?a3)) (not (= ?a1 ?a4)) (not (= ?a2 ?a3)) (not (= ?a2 ?a4)) (not (= ?a3 ?a4))
              )
                   
:effect (and (died ?victim)
             (not (alive ?victim)))
)

(:action kill-if-three-died :parameters (?k ?victim ?r ?a1 ?a2 ?a3 ?a4)
:precondition (and (ROOM ?r) (KILLER ?k) (AGENT ?victim) (AGENT ?a1) (AGENT ?a2) (AGENT ?a3) (AGENT ?a4)
                   (alive ?k) (alive ?victim) (alive ?a1) (died ?a2) (died ?a3) (died ?a4)
                   (in-room ?k ?r) (in-room ?victim ?r)
                   (not (in-room ?a1 ?r))
                   (not (= ?a1 ?a2)) (not (= ?a1 ?a3)) (not (= ?a1 ?a4)) (not (= ?a2 ?a3)) (not (= ?a2 ?a4)) (not (= ?a3 ?a4))
              )
                   
:effect (and (died ?victim)
             (not (alive ?victim)))
)

(:action kill-if-four-died :parameters (?k ?victim ?r ?a1 ?a2 ?a3 ?a4)
:precondition (and (ROOM ?r) (KILLER ?k) (AGENT ?victim) (AGENT ?a1) (AGENT ?a2) (AGENT ?a3) (AGENT ?a4)
                   (alive ?k) (alive ?victim) (died ?a1) (died ?a2) (died ?a3) (died ?a4)
                   (in-room ?k ?r) (in-room ?victim ?r)
                   (not (= ?a1 ?a2)) (not (= ?a1 ?a3)) (not (= ?a1 ?a4)) (not (= ?a2 ?a3)) (not (= ?a2 ?a4)) (not (= ?a3 ?a4))
              )
                   
:effect (and (died ?victim)
             (not (alive ?victim)))
)
)